{
 "title": "NIJIKA GPON / Unifi Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "onu_state",
    "query": {
     "query": "label_values(onu_info{instance=\"192.168.1.1\"}, onu_state)"
    }
   },
   {
    "name": "onu_id",
    "query": {
     "query": "label_values(onu_info{instance=\"192.168.1.1\"}, onu_id)"
    }
   },
   {
    "name": "los_indicator",
    "query": {
     "query": "label_values(onu_info{instance=\"192.168.1.1\"}, los_indicator)"
    }
   },
   {
    "name": "los_description",
    "query": {
     "query": "label_values(onu_info{instance=\"192.168.1.1\"}, los_description)"
    }
   },
   {
    "name": "oltvendorid",
    "query": {
     "query": "label_values(onu_info{instance=\"192.168.1.1\"}, oltvendorid)"
    }
   },
   {
    "name": "gpon_sn",
    "query": {
     "query": "label_values(onu_info{instance=\"192.168.1.1\"}, gpon_sn)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"font-size:medium;display:inline-block;border:1px solid #555;border-radius:6px;padding:10px\">\n<b>ONU STATUS</b>\n<table style=\"width:auto;margin-top:5px\">\n<tr><td>ONT State</td><td><b>$onu_state</b></td></tr>\n<tr><td>ONT ID</td><td>$onu_id</td></tr>\n<tr><td>ONT SN</td><td><code>$gpon_sn</code></td></tr>\n<tr><td>OLT Vendor</td><td><code>$oltvendorid</code></td></tr>\n<tr><td>LOS</td><td><code>$los_indicator</code></td></tr>\n<tr><td colspan=\"2\">$los_description</td></tr>\n</table>\n</div>\n"
   }
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "ONU CPU Usage",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "onu_cpu{instance=\"192.168.1.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "description": "ONU RAM",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "onu_memory{instance=\"192.168.1.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps",
   "type": "gauge",
   "description": "ONU Temps",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "onu_temperature{instance=\"192.168.1.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "onu_up_time_seconds{instance=\"192.168.1.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rx Power",
   "type": "timeseries",
   "description": "ONU Rx Power",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "onu_rx_power{instance=\"192.168.1.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Power",
   "type": "timeseries",
   "description": "ONU Tx Power",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "onu_tx_power{instance=\"192.168.1.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "description": "ONU Voltage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "onu_voltage{instance=\"192.168.1.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bias Current",
   "type": "timeseries",
   "description": "ONU Bias Current",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "onu_bias_current{instance=\"192.168.1.1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}